### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by BLAST1718** [VpsOP/ApexMiner#10]
21-03-15 [00:18:38] [Server thread/CRITICAL]: TypeError: "Argument 2 passed to ApexDev\ApexMiner\tiles\MinerTile::__construct() must be an instance of pocketmine\level\Position, instance of pocketmine\nbt\tag\CompoundTag given, called in phar:///home/container/PocketMine-MP.phar/src/pocketmine/tile/Tile.php on line 116" (EXCEPTION) in "plugins/ApexMiner_dev-9.phar/src/ApexDev/ApexMiner/tiles/MinerTile" at line 33

this happens when i leave the server

**Comment by VpsOP** [comment]
Hey I've updated some code. (removed a lot of lines).
use this build 
[https://poggit.pmmp.io/r/118319/ApexMiner_dev-11.phar](https://poggit.pmmp.io/r/118319/ApexMiner_dev-11.phar)

I tested that leaving & joining the server 10-12 times.
found no issue.

If the issue still occurs pls reopen the issue here.
